/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "lf",
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  printWidth: 100,
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^@local/(.*)$",
    "^@/messages/(.*)$",
    "^@/config/(.*)$",
    "^@/types$",
    "^@/types/(.*)$",
    "^@/graphql/(.*)$",
    "^@/lib/(.*)$",
    "^@/queries$",
    "^@/components/ui(.*)$",
    "^@/components/layout(.*)$",
    "^@/components/(.*)$",
    "^@/hooks/(.*)$",
    "^@/websocket/(.*)$",
    "^@/styles/(.*)$",
    "",
    "public/(.*)$",
    "",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderRemoveUnusedImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ["@ianvs/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
}