import UsernameDialogForm from "@/components/auth/UsernameDialogForm";

import "./globals.css";

import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";

import { getTables } from "@/lib/sdk";
import TableLinks from "@/components/board/TablesLinks";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const tables = await getTables();

  return (
    <html lang="en">
      <body className={jakarta.className}>
        <main className="relative flex min-h-screen flex-col bg-slate-50">
          <UsernameDialogForm />
          {children}
          <TableLinks tables={tables} />
        </main>
      </body>
    </html>
  );
}
